server:
  port: 18083
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
spring:
  cloud:
    stream:
      # 测试可以先后启动 2 个实例 --server.port=8888，广播模式第一个启动的实例的消费者会打印 2 次
      # out是生产者，in是消费者，数字是函数参数位置，destination是队列名
      function:
        # @bean Consumer 方法名，不能有空格
        definition: myMqConsumer;
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          myMqProducer-out-0:
            producer:
              group: test-myMqProducer
          myMqConsumer-in-0:
            consumer:
              # 广播模式
              messageModel: BROADCASTING
      bindings:
        myMqProducer-out-0:
          destination: ggb
        myMqConsumer-in-0:
          destination: ggb
          group: test-myMqConsumer
  datasource:
    name: storageDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test2?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: test2
    password: 123456
    druid:
      max-active: 20
      min-idle: 2
      initial-size: 2
#logging:
#  level:
#    org.springframework.context.support: debug

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      namespace: fe02127c-8494-474f-854c-1518370ba716
      group: SEATA_GROUP
      dataId: seata.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: fe02127c-8494-474f-854c-1518370ba716
      group: SEATA_GROUP
      username: nacos
      password: nacos
